[2024-01-30T03:33:27.111+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: manage_data_lake_dag.local_job_raw_to_formatted scheduled__2024-01-06T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
