[2024-01-30T13:56:27.459+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-30T13:56:22.986051+00:00 [queued]>
[2024-01-30T13:56:27.466+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-30T13:56:22.986051+00:00 [queued]>
[2024-01-30T13:56:27.467+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-30T13:56:27.483+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_raw_to_formatted> on 2024-01-30 13:56:22.986051+00:00
[2024-01-30T13:56:27.489+0000] {standard_task_runner.py:60} INFO - Started process 41604 to run task
[2024-01-30T13:56:27.495+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_raw_to_formatted', 'manual__2024-01-30T13:56:22.986051+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmp20z8carm']
[2024-01-30T13:56:27.498+0000] {standard_task_runner.py:88} INFO - Job 231: Subtask dataproc_job_raw_to_formatted
[2024-01-30T13:56:27.548+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-30T13:56:22.986051+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T13:56:27.625+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_raw_to_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T13:56:22.986051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T13:56:22.986051+00:00'
[2024-01-30T13:56:27.627+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T13:56:27.633+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T13:56:27.638+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T13:56:27.706+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/proto/message.py", line 581, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/proto/marshal/marshal.py", line 228, in to_proto
    pb_value = self.get_rule(proto_type=proto_type).to_proto(value)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/proto/marshal/rules/message.py", line 36, in to_proto
    return self._descriptor(**value)
ValueError: Protocol message SparkJob has no "main_jar_file" field.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2319, in execute
    job_object = self.hook.submit_job(
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 482, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 807, in submit_job
    return client.submit_job(
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/google/cloud/dataproc_v1/services/job_controller/client.py", line 521, in submit_job
    request = jobs.SubmitJobRequest(request)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/proto/message.py", line 609, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/proto/marshal/marshal.py", line 228, in to_proto
    pb_value = self.get_rule(proto_type=proto_type).to_proto(value)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/proto/marshal/rules/message.py", line 36, in to_proto
    return self._descriptor(**value)
ValueError: Protocol message SparkJob has no "main_jar_file" field.
[2024-01-30T13:56:27.713+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=manage_data_lake_dag, task_id=dataproc_job_raw_to_formatted, execution_date=20240130T135622, start_date=20240130T135627, end_date=20240130T135627
[2024-01-30T13:56:27.726+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 231 for task dataproc_job_raw_to_formatted (Protocol message SparkJob has no "main_jar_file" field.; 41604)
[2024-01-30T13:56:27.758+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-30T13:56:27.773+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
