[2024-01-31T07:41:36.349+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-31T07:32:03.310139+00:00 [queued]>
[2024-01-31T07:41:36.355+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-31T07:32:03.310139+00:00 [queued]>
[2024-01-31T07:41:36.356+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-31T07:41:36.371+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_raw_to_formatted> on 2024-01-31 07:32:03.310139+00:00
[2024-01-31T07:41:36.376+0000] {standard_task_runner.py:60} INFO - Started process 135481 to run task
[2024-01-31T07:41:36.382+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_raw_to_formatted', 'manual__2024-01-31T07:32:03.310139+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmpbl5ds28y']
[2024-01-31T07:41:36.385+0000] {standard_task_runner.py:88} INFO - Job 447: Subtask dataproc_job_raw_to_formatted
[2024-01-31T07:41:36.439+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-31T07:32:03.310139+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-31T07:41:36.517+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_raw_to_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T07:32:03.310139+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T07:32:03.310139+00:00'
[2024-01-31T07:41:36.519+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-31T07:41:36.524+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-31T07:41:36.529+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-31T07:41:36.738+0000] {dataproc.py:2329} INFO - Job ac668ab4-f4a3-46e2-97d2-fe50e736f70e submitted successfully.
[2024-01-31T07:41:36.751+0000] {dataproc.py:2363} INFO - Waiting for job ac668ab4-f4a3-46e2-97d2-fe50e736f70e to complete
[2024-01-31T07:42:51.989+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-01-31T07:42:51.994+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 135481. PIDs of all processes in the group: [135481]
[2024-01-31T07:42:51.994+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 135481
[2024-01-31T07:42:51.995+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-31T07:42:52.167+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=135481, status='terminated', exitcode=0, started='07:41:35') (135481) terminated with exit code 0
