[2024-01-29T10:10:37.705+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T10:10:25.443620+00:00 [queued]>
[2024-01-29T10:10:37.711+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T10:10:25.443620+00:00 [queued]>
[2024-01-29T10:10:37.712+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-29T10:10:37.796+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): spark_job_formatted> on 2024-01-29 10:10:25.443620+00:00
[2024-01-29T10:10:37.800+0000] {standard_task_runner.py:60} INFO - Started process 85664 to run task
[2024-01-29T10:10:37.806+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'spark_job_formatted', 'manual__2024-01-29T10:10:25.443620+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmpkk50ns6k']
[2024-01-29T10:10:37.808+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask spark_job_formatted
[2024-01-29T10:10:37.843+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T10:10:25.443620+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-29T10:10:37.898+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='spark_job_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T10:10:25.443620+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T10:10:25.443620+00:00'
[2024-01-29T10:10:37.904+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-29T10:10:37.905+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.hadoop.yarn.resourcemanager.hostname=resourcemanager.fqdn --conf spark.hadoop.yarn.resourcemanager.address=resourcemanager.fqdn:8032 --name arrow-spark --class RawToFormatted --queue root.default --deploy-mode client /home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar gs://data-lake-buck
[2024-01-29T10:10:40.411+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SparkContext: Running Spark version 3.5.0
[2024-01-29T10:10:40.415+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SparkContext: OS info Linux, 5.15.0-1049-gcp, amd64
[2024-01-29T10:10:40.416+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SparkContext: Java version 17.0.9
[2024-01-29T10:10:40.532+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-29T10:10:40.647+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO ResourceUtils: ==============================================================
[2024-01-29T10:10:40.648+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-01-29T10:10:40.649+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO ResourceUtils: ==============================================================
[2024-01-29T10:10:40.651+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SparkContext: Submitted application: RawToFormatted
[2024-01-29T10:10:40.686+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-01-29T10:10:40.701+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2024-01-29T10:10:40.704+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-01-29T10:10:40.788+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SecurityManager: Changing view acls to: juniortemgoua0
[2024-01-29T10:10:40.789+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SecurityManager: Changing modify acls to: juniortemgoua0
[2024-01-29T10:10:40.790+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SecurityManager: Changing view acls groups to:
[2024-01-29T10:10:40.791+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SecurityManager: Changing modify acls groups to:
[2024-01-29T10:10:40.792+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:40 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: juniortemgoua0; groups with view permissions: EMPTY; users with modify permissions: juniortemgoua0; groups with modify permissions: EMPTY
[2024-01-29T10:10:41.314+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO Utils: Successfully started service 'sparkDriver' on port 34723.
[2024-01-29T10:10:41.361+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO SparkEnv: Registering MapOutputTracker
[2024-01-29T10:10:41.414+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO SparkEnv: Registering BlockManagerMaster
[2024-01-29T10:10:41.441+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-01-29T10:10:41.444+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-01-29T10:10:41.496+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-01-29T10:10:41.521+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-de043bd8-3a11-4464-bc7b-a4f02b329956
[2024-01-29T10:10:41.541+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-01-29T10:10:41.608+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-01-29T10:10:41.782+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-01-29T10:10:41.885+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-01-29T10:10:41.945+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:41 INFO SparkContext: Added JAR file:/home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar at spark://instance-1.europe-west9-a.c.data-lake-project-409321.internal:34723/jars/spark_job_2.12-0.1.0.jar with timestamp 1706523040396
[2024-01-29T10:10:42.201+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:42 INFO DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at resourcemanager.fqdn/<unresolved>:8032
[2024-01-29T10:10:43.394+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:43 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:44.395+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:44 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:45.398+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:45 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:46.398+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:46 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:47.399+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:47 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:48.400+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:48 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:49.401+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:49 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:50.404+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:50 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:51.405+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:51 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:52.405+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:52 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:53.437+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:53 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:54.438+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:54 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:55.440+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:55 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:56.442+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:56 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:57.442+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:57 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:58.443+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:58 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:59.443+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:59 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:00.447+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:01.447+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:02.448+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:02.462+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:02 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 1 failover attempts. Trying to failover after sleeping for 29799ms.
[2024-01-29T10:11:33.299+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:33 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:34.300+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:34 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:35.301+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:35 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:36.301+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:36 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:37.303+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:37 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:38.306+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:38 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:39.307+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:39 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:40.307+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:40 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:41.308+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:41 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:42.308+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:42 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:11:42.326+0000] {spark_submit.py:571} INFO - 24/01/29 10:11:42 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 2 failover attempts. Trying to failover after sleeping for 41761ms.
[2024-01-29T10:12:25.143+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:25 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:26.144+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:26 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:27.144+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:27 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:28.145+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:28 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:29.145+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:29 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:30.149+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:30 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:31.149+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:31 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:32.150+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:32 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:33.150+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:33 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:34.151+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:34 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:12:34.167+0000] {spark_submit.py:571} INFO - 24/01/29 10:12:34 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 3 failover attempts. Trying to failover after sleeping for 38847ms.
[2024-01-29T10:13:14.036+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:14 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:15.037+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:15 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:16.037+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:16 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:17.038+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:17 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:18.038+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:18 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:19.041+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:19 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:20.042+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:20 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:21.042+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:21 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:22.043+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:22 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:23.043+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:23 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:23.061+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:23 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 4 failover attempts. Trying to failover after sleeping for 23685ms.
[2024-01-29T10:13:47.762+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:47 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:48.763+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:48 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:49.764+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:49 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:50.764+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:50 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:51.765+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:51 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:52.769+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:52 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:53.770+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:53 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:54.770+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:54 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:55.771+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:55 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:56.771+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:56 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:13:56.787+0000] {spark_submit.py:571} INFO - 24/01/29 10:13:56 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 5 failover attempts. Trying to failover after sleeping for 29894ms.
[2024-01-29T10:14:27.705+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:27 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:28.705+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:28 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:29.706+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:29 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:30.706+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:30 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:31.707+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:31 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:32.710+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:32 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:33.711+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:33 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:34.711+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:34 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:35.712+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:35 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:36.713+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:36 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:14:36.729+0000] {spark_submit.py:571} INFO - 24/01/29 10:14:36 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 6 failover attempts. Trying to failover after sleeping for 39337ms.
[2024-01-29T10:15:17.083+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:17 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:18.083+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:18 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:19.084+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:19 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:20.084+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:20 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:21.085+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:21 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:22.088+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:22 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:23.089+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:23 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:24.089+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:24 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:25.090+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:25 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:26.090+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:26 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:15:26.106+0000] {spark_submit.py:571} INFO - 24/01/29 10:15:26 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 7 failover attempts. Trying to failover after sleeping for 44217ms.
[2024-01-29T10:16:11.343+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:11 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:12.344+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:12 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:13.344+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:13 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:14.345+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:14 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:15.345+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:15 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:16.348+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:16 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:17.349+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:17 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:18.349+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:18 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:19.350+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:19 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:20.351+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:20 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:20.369+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:20 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 8 failover attempts. Trying to failover after sleeping for 27748ms.
[2024-01-29T10:16:49.136+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:49 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:50.137+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:50 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:51.137+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:51 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:52.138+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:52 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:53.139+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:53 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:54.142+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:54 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:55.142+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:55 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:56.143+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:56 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:57.143+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:57 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:58.144+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:58 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:16:58.160+0000] {spark_submit.py:571} INFO - 24/01/29 10:16:58 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 9 failover attempts. Trying to failover after sleeping for 38575ms.
[2024-01-29T10:17:37.758+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:37 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:38.759+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:38 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:39.759+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:39 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:40.760+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:40 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:41.760+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:41 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:42.763+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:42 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:43.764+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:43 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:44.765+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:44 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:45.765+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:45 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:46.766+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:46 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:17:46.782+0000] {spark_submit.py:571} INFO - 24/01/29 10:17:46 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 10 failover attempts. Trying to failover after sleeping for 24670ms.
[2024-01-29T10:18:12.474+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:12 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:13.474+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:13 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:14.475+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:14 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:15.475+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:15 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:16.476+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:16 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:17.479+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:17 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:18.479+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:18 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:19.480+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:19 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:20.481+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:20 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:21.481+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:21 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:18:21.498+0000] {spark_submit.py:571} INFO - 24/01/29 10:18:21 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 11 failover attempts. Trying to failover after sleeping for 42695ms.
[2024-01-29T10:19:05.211+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:05 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:06.211+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:06 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:07.212+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:07 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:08.212+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:08 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:09.213+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:09 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:10.216+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:10 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:11.217+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:11 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:12.218+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:12 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:13.218+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:13 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:14.219+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:14 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:14.235+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:14 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 12 failover attempts. Trying to failover after sleeping for 21849ms.
[2024-01-29T10:19:37.101+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:37 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:38.101+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:38 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:39.102+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:39 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:40.102+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:40 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:41.103+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:41 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:42.107+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:42 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:43.106+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:43 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:44.107+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:44 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:45.107+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:45 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:46.108+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:46 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:19:46.126+0000] {spark_submit.py:571} INFO - 24/01/29 10:19:46 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 13 failover attempts. Trying to failover after sleeping for 37888ms.
[2024-01-29T10:20:25.035+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:25 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:26.034+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:26 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:27.035+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:27 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:28.035+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:28 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:29.036+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:29 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:30.039+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:30 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:31.040+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:31 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:32.040+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:32 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:33.041+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:33 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:34.042+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:34 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:20:34.059+0000] {spark_submit.py:571} INFO - 24/01/29 10:20:34 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 14 failover attempts. Trying to failover after sleeping for 31985ms.
[2024-01-29T10:21:07.068+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:07 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:08.068+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:08 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:09.069+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:09 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:10.069+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:10 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:11.070+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:11 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:12.073+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:12 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:13.074+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:13 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:14.074+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:14 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:15.075+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:15 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:16.075+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:16 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:16.092+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:16 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 15 failover attempts. Trying to failover after sleeping for 37876ms.
[2024-01-29T10:21:54.986+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:54 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:55.986+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:55 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:56.987+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:56 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:57.987+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:57 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:58.988+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:58 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:21:59.991+0000] {spark_submit.py:571} INFO - 24/01/29 10:21:59 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:00.991+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:01.992+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:02.993+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:03.993+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:03 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:04.012+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:04 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 16 failover attempts. Trying to failover after sleeping for 41637ms.
[2024-01-29T10:22:46.665+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:46 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:47.666+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:47 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:48.666+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:48 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:49.667+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:49 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:50.668+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:50 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:51.671+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:51 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:52.671+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:52 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:53.672+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:53 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:54.672+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:54 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:55.674+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:55 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:22:55.691+0000] {spark_submit.py:571} INFO - 24/01/29 10:22:55 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 17 failover attempts. Trying to failover after sleeping for 20893ms.
[2024-01-29T10:23:17.601+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:17 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:18.602+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:18 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:19.602+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:19 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:20.603+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:20 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:21.604+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:21 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:22.607+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:22 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:23.607+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:23 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:24.608+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:24 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:25.608+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:25 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:26.609+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:26 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:23:26.625+0000] {spark_submit.py:571} INFO - 24/01/29 10:23:26 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 18 failover attempts. Trying to failover after sleeping for 33311ms.
[2024-01-29T10:24:00.954+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:01.955+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:02.955+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:03.956+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:03 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:04.957+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:04 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:05.960+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:05 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:06.960+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:06 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:07.961+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:07 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:08.961+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:08 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:09.962+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:09 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:09.979+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:09 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 19 failover attempts. Trying to failover after sleeping for 33175ms.
[2024-01-29T10:24:44.171+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:44 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:45.172+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:45 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:46.172+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:46 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:47.173+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:47 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:48.173+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:48 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:49.177+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:49 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:50.177+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:50 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:51.178+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:51 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:52.179+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:52 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:53.179+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:53 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:24:53.195+0000] {spark_submit.py:571} INFO - 24/01/29 10:24:53 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 20 failover attempts. Trying to failover after sleeping for 25392ms.
[2024-01-29T10:25:19.605+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:19 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:20.605+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:20 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:21.606+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:21 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:22.607+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:22 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:23.607+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:23 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:24.610+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:24 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:25.610+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:25 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:26.611+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:26 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:27.611+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:27 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:28.612+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:28 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:28.628+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:28 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 21 failover attempts. Trying to failover after sleeping for 27722ms.
[2024-01-29T10:25:57.367+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:57 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:58.367+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:58 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:25:59.368+0000] {spark_submit.py:571} INFO - 24/01/29 10:25:59 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:00.368+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:01.369+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:02.372+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:03.372+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:03 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:04.373+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:04 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:05.373+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:05 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:06.374+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:06 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:06.391+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:06 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 22 failover attempts. Trying to failover after sleeping for 25293ms.
[2024-01-29T10:26:32.701+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:32 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:33.702+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:33 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:34.702+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:34 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:35.703+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:35 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:36.704+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:36 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:37.707+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:37 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:38.707+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:38 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:39.708+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:39 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:40.708+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:40 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:41.709+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:41 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:26:41.726+0000] {spark_submit.py:571} INFO - 24/01/29 10:26:41 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 23 failover attempts. Trying to failover after sleeping for 27073ms.
[2024-01-29T10:27:09.819+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:09 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:10.820+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:10 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:11.820+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:11 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:12.821+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:12 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:13.821+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:13 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:14.824+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:14 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:15.825+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:15 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:16.825+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:16 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:17.826+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:17 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:18.826+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:18 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:27:18.844+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:18 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 24 failover attempts. Trying to failover after sleeping for 39733ms.
[2024-01-29T10:27:59.598+0000] {spark_submit.py:571} INFO - 24/01/29 10:27:59 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:00.598+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:01.598+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:02.599+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:03.600+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:03 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:04.603+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:04 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:05.603+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:05 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:06.604+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:06 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:07.605+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:07 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:08.605+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:08 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:08.621+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:08 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 25 failover attempts. Trying to failover after sleeping for 22741ms.
[2024-01-29T10:28:32.381+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:32 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:33.381+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:33 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:34.382+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:34 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:35.382+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:35 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:36.383+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:36 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:37.385+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:37 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:38.386+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:38 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:39.386+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:39 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:40.387+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:40 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:41.388+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:41 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:28:41.404+0000] {spark_submit.py:571} INFO - 24/01/29 10:28:41 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 26 failover attempts. Trying to failover after sleeping for 17875ms.
[2024-01-29T10:29:00.299+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:01.300+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:02.300+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:03.301+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:03 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:04.301+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:04 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:05.304+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:05 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:06.304+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:06 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:07.305+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:07 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:08.306+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:08 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:09.306+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:09 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:09.323+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:09 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 27 failover attempts. Trying to failover after sleeping for 44576ms.
[2024-01-29T10:29:54.916+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:54 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:55.916+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:55 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:56.917+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:56 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:57.917+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:57 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:58.918+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:58 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:29:59.921+0000] {spark_submit.py:571} INFO - 24/01/29 10:29:59 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:00.922+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:01.923+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:02.923+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:03.923+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:03 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:03.942+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:03 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 28 failover attempts. Trying to failover after sleeping for 24951ms.
[2024-01-29T10:30:29.910+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:29 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:30.911+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:30 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:31.911+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:31 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:32.912+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:32 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:33.912+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:33 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:34.915+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:34 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:35.915+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:35 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:36.916+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:36 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:37.916+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:37 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:38.917+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:38 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:30:38.933+0000] {spark_submit.py:571} INFO - 24/01/29 10:30:38 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 29 failover attempts. Trying to failover after sleeping for 32599ms.
[2024-01-29T10:31:12.550+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:12 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:13.551+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:13 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:14.551+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:14 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:15.552+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:15 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:16.552+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:16 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:17.555+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:17 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:18.555+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:18 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:19.556+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:19 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:20.556+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:20 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:21.557+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:31:21.578+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 ERROR SparkContext: Error initializing SparkContext.
[2024-01-29T10:31:21.578+0000] {spark_submit.py:571} INFO - java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
[2024-01-29T10:31:21.578+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source)
[2024-01-29T10:31:21.578+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-01-29T10:31:21.579+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2024-01-29T10:31:21.579+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2024-01-29T10:31:21.579+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2024-01-29T10:31:21.579+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:841)
[2024-01-29T10:31:21.579+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2024-01-29T10:31:21.579+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2024-01-29T10:31:21.579+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2024-01-29T10:31:21.580+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2024-01-29T10:31:21.580+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2024-01-29T10:31:21.580+0000] {spark_submit.py:571} INFO - at jdk.proxy2/jdk.proxy2.$Proxy28.getNewApplication(Unknown Source)
[2024-01-29T10:31:21.580+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getNewApplication(ApplicationClientProtocolPBClientImpl.java:286)
[2024-01-29T10:31:21.580+0000] {spark_submit.py:571} INFO - at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[2024-01-29T10:31:21.580+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-29T10:31:21.580+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-01-29T10:31:21.581+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2024-01-29T10:31:21.581+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2024-01-29T10:31:21.581+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2024-01-29T10:31:21.581+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2024-01-29T10:31:21.581+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2024-01-29T10:31:21.581+0000] {spark_submit.py:571} INFO - at jdk.proxy2/jdk.proxy2.$Proxy29.getNewApplication(Unknown Source)
[2024-01-29T10:31:21.581+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getNewApplication(YarnClientImpl.java:284)
[2024-01-29T10:31:21.582+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createApplication(YarnClientImpl.java:292)
[2024-01-29T10:31:21.582+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:195)
[2024-01-29T10:31:21.582+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
[2024-01-29T10:31:21.582+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2024-01-29T10:31:21.582+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:604)
[2024-01-29T10:31:21.582+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2888)
[2024-01-29T10:31:21.582+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:1099)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:1093)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at RawToFormatted$.main(RawToFormatted.scala:13)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at RawToFormatted.main(RawToFormatted.scala)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-29T10:31:21.583+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-01-29T10:31:21.584+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-29T10:31:21.585+0000] {spark_submit.py:571} INFO - Caused by: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
[2024-01-29T10:31:21.585+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source)
[2024-01-29T10:31:21.585+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-01-29T10:31:21.585+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2024-01-29T10:31:21.585+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2024-01-29T10:31:21.585+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2024-01-29T10:31:21.585+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:841)
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:662)
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - ... 38 more
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - Caused by: java.net.UnknownHostException
[2024-01-29T10:31:21.586+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:664)
[2024-01-29T10:31:21.587+0000] {spark_submit.py:571} INFO - ... 42 more
[2024-01-29T10:31:21.587+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-01-29T10:31:21.609+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO SparkUI: Stopped Spark web UI at http://instance-1.europe-west9-a.c.data-lake-project-409321.internal:4040
[2024-01-29T10:31:21.618+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to send shutdown message before the AM has registered!
[2024-01-29T10:31:21.630+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
[2024-01-29T10:31:21.634+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO YarnClientSchedulerBackend: Shutting down all executors
[2024-01-29T10:31:21.637+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
[2024-01-29T10:31:21.644+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO YarnClientSchedulerBackend: YARN client scheduler backend Stopped
[2024-01-29T10:31:21.666+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-01-29T10:31:21.675+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO MemoryStore: MemoryStore cleared
[2024-01-29T10:31:21.676+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO BlockManager: BlockManager stopped
[2024-01-29T10:31:21.686+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-01-29T10:31:21.687+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 WARN MetricsSystem: Stopping a MetricsSystem that is not running
[2024-01-29T10:31:21.690+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-01-29T10:31:21.701+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO SparkContext: Successfully stopped SparkContext
[2024-01-29T10:31:21.702+0000] {spark_submit.py:571} INFO - Exception in thread "main" java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
[2024-01-29T10:31:21.702+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source)
[2024-01-29T10:31:21.702+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-01-29T10:31:21.702+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2024-01-29T10:31:21.702+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2024-01-29T10:31:21.703+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2024-01-29T10:31:21.703+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:841)
[2024-01-29T10:31:21.703+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2024-01-29T10:31:21.703+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2024-01-29T10:31:21.703+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2024-01-29T10:31:21.703+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2024-01-29T10:31:21.703+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2024-01-29T10:31:21.704+0000] {spark_submit.py:571} INFO - at jdk.proxy2/jdk.proxy2.$Proxy28.getNewApplication(Unknown Source)
[2024-01-29T10:31:21.704+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getNewApplication(ApplicationClientProtocolPBClientImpl.java:286)
[2024-01-29T10:31:21.704+0000] {spark_submit.py:571} INFO - at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[2024-01-29T10:31:21.704+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-29T10:31:21.704+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-01-29T10:31:21.704+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2024-01-29T10:31:21.704+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2024-01-29T10:31:21.706+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2024-01-29T10:31:21.706+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2024-01-29T10:31:21.706+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2024-01-29T10:31:21.706+0000] {spark_submit.py:571} INFO - at jdk.proxy2/jdk.proxy2.$Proxy29.getNewApplication(Unknown Source)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getNewApplication(YarnClientImpl.java:284)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createApplication(YarnClientImpl.java:292)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:195)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:604)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2888)
[2024-01-29T10:31:21.707+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:1099)
[2024-01-29T10:31:21.708+0000] {spark_submit.py:571} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-01-29T10:31:21.708+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:1093)
[2024-01-29T10:31:21.708+0000] {spark_submit.py:571} INFO - at RawToFormatted$.main(RawToFormatted.scala:13)
[2024-01-29T10:31:21.708+0000] {spark_submit.py:571} INFO - at RawToFormatted.main(RawToFormatted.scala)
[2024-01-29T10:31:21.708+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-29T10:31:21.708+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-01-29T10:31:21.711+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-29T10:31:21.711+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-01-29T10:31:21.711+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
[2024-01-29T10:31:21.711+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - Caused by: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
[2024-01-29T10:31:21.712+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:841)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:662)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2024-01-29T10:31:21.713+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - ... 38 more
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - Caused by: java.net.UnknownHostException
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:664)
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - ... 42 more
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO ShutdownHookManager: Shutdown hook called
[2024-01-29T10:31:21.714+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO ShutdownHookManager: Deleting directory /tmp/spark-ee83ff88-7214-4635-99db-6baac6270038
[2024-01-29T10:31:21.715+0000] {spark_submit.py:571} INFO - 24/01/29 10:31:21 INFO ShutdownHookManager: Deleting directory /tmp/spark-d794d65f-de25-409c-aa28-db208c1af5a9
[2024-01-29T10:31:21.753+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.hadoop.yarn.resourcemanager.hostname=resourcemanager.fqdn --conf spark.hadoop.yarn.resourcemanager.address=resourcemanager.fqdn:8032 --name arrow-spark --class RawToFormatted --queue root.default --deploy-mode client /home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar gs://data-lake-buck. Error code is: 1.
[2024-01-29T10:31:21.757+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=manage_data_lake_dag, task_id=spark_job_formatted, execution_date=20240129T101025, start_date=20240129T101037, end_date=20240129T103121
[2024-01-29T10:31:21.770+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 91 for task spark_job_formatted (Cannot execute: spark-submit --master yarn --conf spark.hadoop.yarn.resourcemanager.hostname=resourcemanager.fqdn --conf spark.hadoop.yarn.resourcemanager.address=resourcemanager.fqdn:8032 --name arrow-spark --class RawToFormatted --queue root.default --deploy-mode client /home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar gs://data-lake-buck. Error code is: 1.; 85664)
[2024-01-29T10:31:21.789+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-29T10:31:21.800+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
