[2024-01-31T08:04:12.818+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: manage_data_lake_dag.extract_data_and_load_to_gs manual__2024-01-31T08:04:07.888594+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
